merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),


    # path('bands/', views.band_list, name='band-list'),
    path('bands/', views.BandListView.as_view(), name='band-list'),
    path('offers/', views.OfferListView.as_view(), name='offer-list'),

    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_add, name='band-add'),
    path('bands/update/<int:band_id>/', views.band_update, name='band-update'),
    path('bands/remove/<int:band_id>/', views.band_remove, name='band-remove'), 

    # path('offers/', views.offer_list, name='offer-list'),
    path('offers/<int:offer_id>/', views.offer_detail, name='offer-detail'),
    path('offers/add/', views.offer_add, name='offer-add'),
    path('offers/update/<int:offer_id>/', views.offer_update, name='offer-update'),
    path('offers/remove/<int:offer_id>/', views.offer_remove, name='offer-remove'),
    
    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent')

]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.


class Band(models.Model):

    class Genre(models.TextChoices):
        ROCK = 'ROCK'
        RAP = 'RAP'
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        METAL = 'METAL'

    def __str__(self) -> str:
        return f'{self.name}'


    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.TextField(null=True, blank=True)
    year_formed = models.fields.PositiveIntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_page = models.fields.URLField(null=True, blank=True)

class Offer(models.Model):


    class OfferType(models.TextChoices):
        RECORDS = 'RECORDS'
        CLOTHING = 'CLOTHES'
        POSTERS = 'POSTERS'
        FURNITURE = 'FURNITU'
        MISCELLANEOUS = 'MISC'

    def __str__(self) -> str:
        return f'{self.title}'


    title = models.fields.CharField(max_length=100)
    description = models.fields.TextField(null=True)
    year = models.fields.PositiveIntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2022)])
    offer_type = models.fields.CharField(choices=OfferType.choices, max_length=7)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms
from listings.models import Band, Offer


class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
   class Meta:
      model = Band
      fields = '__all__' # si je veux copier tous les champs du Model Band
      # exclude = ("official_page",) # si je veux exclure certains champs. La "," est requise.

class OfferForm(forms.ModelForm):
   class Meta:
      model = Offer
      fields = '__all__'

merchex/listings/views.py
from django.shortcuts import render
from listings.models import Band, Offer
from listings.forms import ContactUsForm, BandForm, OfferForm
from django.core.mail import send_mail
from django.shortcuts import redirect 
from django.views.generic import ListView
# Create your views here.
def home(request):

    bands = Band.objects.all()
    toto = ''
    for band in bands : 
        toto += f'<div>{band.name}</div>'

    return render(request, 'listings/home.html', {'bands': bands})    
    # return render(request, 'listings/home.html')


# *************************************************
# ******************* BLOC BAND *******************

class BandListView(ListView):
    model: object = Band
    template_name: str = 'listings/band_list.html'
    context_object_name: str = 'bands'


# def band_list(request):
#     bands = Band.objects.all()
#     return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, band_id): 
    band = Band.objects.get(id=band_id)  # nous insérons cette ligne pour obtenir le Band avec cet id
    print(band)
    return render(request, 'listings/band_detail.html', {'band' : band })


def band_add(request): 

    if request.method == "POST":
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:        
        form = BandForm()
    
    return render(request, 'listings/band_add.html', {'form': form})

def band_update(request, band_id): 
    band = Band.objects.get(id=band_id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance = band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance = band)
    
    return render(request, 'listings/band_update.html',{'form': form})

def band_remove(request, band_id):
    band = Band.objects.get(id=band_id)

    if request.method == 'POST':
        band.delete()
        return redirect('band-list')

    return render(request, 'listings/band_remove.html', {'band' : band })

# *************************************************
# ******************* BLOC OFFER ******************

class OfferListView(ListView):
    model: object = Offer
    template_name: str = 'listings/offer_list.html'
    context_object_name: str = 'offers'

# def offer_list(request):

#     offers = Offer.objects.all()

#     return render(request, 'listings/offer_list.html', {'offers': offers})


def offer_detail(request, offer_id):
    offer = Offer.objects.get(id=offer_id)
    return render(request,'listings/offer_detail.html', {'offer': offer})

def offer_add(request):

    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid():
            offer = form.save()
            return redirect('offer-detail', offer.id)
    else:
        form = OfferForm()

    form = OfferForm()

    return render(request, 'listings/offer_add.html',{'form': form})

def offer_update(request, offer_id):
    offer = Offer.objects.get(id=offer_id)
    
    if request.method == 'POST':
        form = OfferForm(request.POST, instance = offer)
        if form.is_valid():
            offer = form.save()
            return redirect('offer-detail', offer.id)
    else:
        form = OfferForm(instance = offer)

    return render(request, 'listings/offer_update.html', {'form' : form})

def offer_remove(request, offer_id):
    offer = Offer.objects.get(id = offer_id)

    if request.method == 'POST':
        offer.delete()
        return redirect('offer-list')

    return render(request, 'listings/offer_remove.html', {'offer' : offer})


def about(request):

    return render(request, 'listings/about.html')


def contact(request):


    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject= f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message= form.cleaned_data['message'],
                from_email= form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            # return redirect('about')
            return redirect('email-sent')

    else:
        form = ContactUsForm() 


    return render(request,'listings/contact.html',{'form': form})


def email_sent(request):

    return render(request, 'listings/email_sent.html')

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
        <h2>About</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis doloribus autem neque vero unde sit, error cum possimus iusto expedita quod a in maiores, cumque culpa consequatur repudiandae facilis natus!</p>    
            <br>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis possimus praesentium, illo expedita iusto voluptatem iste omnis totam perferendis quod consequuntur inventore neque. Deleniti, debitis unde. Consectetur sint sapiente eveniet!</p>
            <br>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A debitis veniam consectetur error enim natus aperiam cumque adipisci. Consequuntur animi dolore eos accusantium quos possimus neque modi vitae ducimus suscipit!</p>
{% endblock %}

merchex/listings/templates/listings/band_add.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>Ajouter un nouveau groupe :</h2>
<p>
    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
      </form>
</p>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active | yesno}}</li>
 {% if band.official_page %}
 <li>
    <a href="{{ band.official_page }}" target="_blank">{{ band.official_page}}</a>
</li>
{% endif %}
</ul>

<p>{{ band.biography }}</p>



<p>Articles lié à cet artiste :</p>
{% for offer in band.offer_set.all %}

<ul>
    <li>
          <a href="{% url 'offer-detail' offer.id %}">
        {{ offer.title }}   
   </a>  
    </li>
</ul>

    {% endfor %}
<span><a href="{% url 'band-update' band.id %}">Modifier</a> / <a href="{% url 'band-remove' band.id %}">Supprimer</a> / <a href="{% url 'band-list' %}">Retour</a></span>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mes groupes</h1>
<a href="{% url 'band-add' %}">Ajouter un groupe</a>

<ul>
{% for band in bands %}
<li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a> / <a href="{% url 'band-update' band.id %}">Modifier</a> </li>
{% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/band_remove.html
{% extends 'listings/base.html' %}

{% block content %}
        <h2>remove band</h2>


        <p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Supprimer">
{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
        <h2>update</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Envoyer">
        </form>
{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}


<html>
    <head><title>Merchex</title>
        <!-- <link rel="stylesheet" href="../../static/listings/styles.css"/> -->
        <link rel="stylesheet" href="{% static 'listings/reset.css' %}" />
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />

    </head>
    <body>
        
        <header>
            <h1><a href="{% url 'home' %}" id="title">Merchex</a></h1>
            <nav>
                <a href="{% url 'band-list' %}">Groupes</a>
                <a href="{% url 'offer-list' %}">Offres</a>

                <a href="{% url 'contact' %}">Nous contacter</a>
                <a href="{% url 'about' %}">A propos de nous</a>
            </nav>
        </header>
        {% block content %}{% endblock %}
        
    </body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
        <h2>email sent</h2>

        <p>Votre email a bien été envoyé</p>
        


{% endblock %}

merchex/listings/templates/listings/home.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Homepage</h1>
<p>
    bienvenido
</p>

{% endblock %}

merchex/listings/templates/listings/offer_add.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>Ajouter une nouvelle offre :</h2>
<p>
    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
      </form>
</p>

{% endblock %}

merchex/listings/templates/listings/offer_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ offer.title }}</h2>

 <p>Type : {{ offer.get_offer_type_display }} de {{ offer.year }}</p>
<ul>
 <li>Genre : {{ offer.description }}</li>

 {% if offer.band %}
 <li>
    Cet article est rattaché à :
        {{ offer.band }}    
</li>
{% endif %}
</ul>

<span><a  href="{% url 'offer-update' offer.id %}">Modifier</a> / <a  href="{% url 'offer-remove' offer.id %}">Supprimer</a> /<a  href="{% url 'offer-list' %}">Retour aux offres</a></span>

{% endblock %}

merchex/listings/templates/listings/offer_list.html
{% extends 'listings/base.html' %}

{% block content %}

        <h2>ma page d'offre</h2>
        <a href="{% url 'offer-add' %}">Ajouter une offre</a>

        <p>J'ai {{ offers|length }} offres.</p>

        
        <ul>
            {% for offer in offers %}
        <li>
                <a href="{% url 'offer-detail' offer.id %}">
                     {{ offer.title }}   
                </a> / <a  href="{% url 'offer-update' offer.id %}">Modifier</a>
        </li>
        {% endfor %}     
        </ul>
       

{% endblock %}

merchex/listings/templates/listings/offer_remove.html
{% extends 'listings/base.html' %}

{% block content %}
        <h2>remove band</h2>


        <p>Etes-vous sûr de vouloir supprimer l'offre : {{ offer.title }} ?</p>

        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Supprimer">
{% endblock %}

merchex/listings/templates/listings/offer_update.html
{% extends 'listings/base.html' %}

{% block content %}
        <h2>update offer</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Envoyer" novalidation>
        </form>
{% endblock %}